test

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -37,8 +37,20 @@ jobs:
             ${{ env.MY_STRING }}
           reactions: eyes, rocket
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#      - name: display string
-#        shell: bash
-#        run: |
-#          echo "The string is: ${{ steps.foo.outputs.filter-log }}"
-##
+      - name: display string
+        run: exit 1
+      - name: test
+        run: echo "fail"
+  slack-notification:
+    name: Slack notification
+    if: failure()
+    runs-on: ubuntu-latest
+    steps:
+      - name: slack alert
+        uses: rtCamp/action-slack-notify@v2
+        with:
+          SLACK_WEBHOOK: https://hooks.slack.com/services/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
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_MESSAGE: testw failed on ${{ github.repository }}, <@U04BECLQS4A>
+          SLACK_TITLE: FAILED
+          SLACK_USERNAME: Actions
