ok

diff --git a/.github/workflows/webhook.yaml b/.github/workflows/webhook.yaml
--- a/.github/workflows/webhook.yaml
+++ b/.github/workflows/webhook.yaml
@@ -11,9 +11,20 @@ jobs:
         run: exit 0
       - name: test
         run: echo "fail"
+  fail_job2:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: check firt
+        run: echo "ok"
+      - name: display string
+        run: exit 1
+      - name: test
+        run: echo "fail"
   slack-notification:
     name: Slack notification
-#    if: always() && (needs.fail_job.result == 'failure')
+    needs: [fail_job, fail_job2]
+    if: always() && (needs.fail_job2.result == 'failure')
     runs-on: ubuntu-latest
     steps:
       - name: slack alert
